version: '3.8'

services:
    # Service de l'application Laravel
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: flochic-laravel-app
        container_name: flochic-laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel  # Utiliser le même réseau 'laravel'

    angular:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: flochic-angular-app
        ports:
            - "4200:80"
        networks:
            - laravel  # Utiliser le réseau 'laravel' ici aussi

    # Service de la base de données PostgreSQL
    db:
        image: postgres:13
        container_name: flochic_laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: flochic_backend
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: passer
        ports:
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - laravel  # Réseau 'laravel'

    # Service du serveur Nginx
    web:
        image: nginx:latest
        container_name: flochic_laravel_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel  # Réseau 'laravel'

networks:
    laravel:
        driver: bridge  # Un seul réseau 'laravel' pour tous les services

volumes:
    dbdata:
        driver: local
